sonar.projectKey=jiangxincode_childhood
sonar.projectName=childhood
sonar.organization=jiangxincode-github

sonar.sources=apps
sonar.tests=apps
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=sonar-report.xml
